import os.path
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import filetest
import numpy as np
import cv2 as cv
from cryptography.fernet import Fernet
# from tkinter import *
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage,messagebox,filedialog,END,simpledialog



OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\dwx1284808\Documents\Extract Page\assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("931x554")
window.configure(bg = "#FFFFFF")
def filepath():
    stego_path=filedialog.askopenfilename()
    entry_1.delete(0,END)
    entry_1.insert(0,stego_path.strip())

def filepath1():
    outpath=filedialog.asksaveasfilename()
    entry_2.delete(0,END)
    entry_2.insert(0,outpath.strip())

def extract():
        stego_path = entry_1.get()
        output = entry_2.get()
        stego_size=os.path.getsize(stego_path)
        revert_check=filetest.revert_img(stego_path)
        if type(revert_check) != str:
            entry_3.insert(END, f'Stego-image size: {stego_size//1024} KB\n')
            entry_3.insert(END,"Hidden-File: YES\n")
            entry_3.insert(END,f'File type: {revert_check[2]}\n')
            entry_3.insert(END,f'Password-Detected: {revert_check[0]}\n')
            entry_3.insert(END, f'Password Length: {len(revert_check[1])}\n')
            entry_3.insert(END,f'Packets_segments: {revert_check[4]}\n')




            if revert_check[5]==revert_check[1]:
                filetest.final_revert(revert_check[6],revert_check[5],revert_check[2],revert_check[3],output)
                messagebox.showinfo(title='Success', message="Extraction successful")
            elif revert_check[5]=='N/A' and revert_check[1]!=revert_check[5]:
                filetest.final_revert(revert_check[6],revert_check[5],revert_check[2],revert_check[3],output)
                messagebox.showinfo(title='Success', message="Extraction successful")
            else:
                messagebox.showerror(title='error',message='wrong password')
                return
        else:
            entry_3.delete(END,END)
            entry_3.insert(END,"NO HIDDEN FILE DETECTED")
            messagebox.showinfo(title='No Message found',message='No hidden information in the image')
            return


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 554,
    width = 931,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    0.0,
    0.0,
    anchor="nw",
    text="Delafuente Steg-Tool",
    fill="#392F2F",
    font=("Georgia", 15 * -1)
)

canvas.create_text(
    111.0,
    101.0,
    anchor="nw",
    text="Stego Image Path",
    fill="#000000",
    font=("Georgia", 15 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    445.0,
    110.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFF8F8",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=276.0,
    y=99.0,
    width=338.0,
    height=20.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
bg='white',
    highlightthickness=0,
    command=filepath,
    relief="flat"
)
button_1.place(
    x=630.0,
    y=101.0,
    width=37.0,
    height=19.0
)
def test():
    entry_3.insert(0,'fuck test')

canvas.create_text(
    111.0,
    188.0,
    anchor="nw",
    text="Output Folder",
    fill="#000000",
    font=("Georgia", 15 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    445.0,
    197.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFF8F8",
    fg="#000716",
    highlightthickness=0,
)

entry_2.place(
    x=276.0,
    y=186.0,
    width=338.0,
    height=20.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
bg='white',
    highlightthickness=0,
    command=filepath1,
    relief="flat"
)
button_2.place(
    x=630.0,
    y=188.0,
    width=37.0,
    height=19.0
)

canvas.create_text(
    776.0,
    334.0,
    anchor="nw",
    text="Details Report",
    fill="#000000",
    font=("Georgia", 15 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    824.0,
    453.5,
    image=entry_image_3
)
entry_3 = Text(
    bd=0,
    bg="#F6EBEB",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=728.0,
    y=353.0,
    width=192.0,
    height=199.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    bg='white',
    highlightthickness=0,
    command=extract,
    relief="flat"
)
button_3.place(
    x=402.0,
    y=362.0,
    width=106.0,
    height=38.0
)
window.resizable(False, False)

window.mainloop()
