import os.path
from cryptography.fernet import Fernet
import numpy as np
import filetest
import cv2 as cv
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage,filedialog,END,messagebox,simpledialog


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\dwx1284808\PycharmProjects\pythonProject\Final year project\assets\frame1")

pasword='N/A'
def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("931x648")
window.configure(bg = "#FFFFFF")
cover_path=''
def file_path():
    cover_path=filedialog.askopenfilename()
    entry_1.delete(0,END)
    entry_1.insert(0,cover_path.strip())

def file_path1():
    filepath=filedialog.askopenfilename()
    entry_2.delete(0,END)
    entry_2.insert(0,filepath.strip())

def file_path2():
    outpath=filedialog.asksaveasfilename(defaultextension='png')
    entry_3.delete(0,END)
    entry_3.insert(0,outpath.strip())

def hide_click():
    cover_img=entry_1.get()
    secret=entry_2.get()
    output=entry_3.get()
    cover_size = os.path.getsize(cover_img)
    if not cover_img:
        messagebox.showerror(title='Empty field',message='Kindly provide a Cover image to hide your data!!')
        return
    if not secret:
        messagebox.showerror(title='Empty field',message='You need to enter the location of the data!!')
        return
    if not output:
        messagebox.showerror(title='Empty field', message='Choose a location for the Stego_image!!')
        return
    cover_img=cv.imread(cover_img)
    cover_img_len=len(filetest.test(cover_img))
    file_extension = os.path.splitext(secret)[1]
    key = Fernet.generate_key()
    h=Fernet(key)
    with open(secret,'rb') as file:
        end = file.read() + '.$+'.encode()
        end=h.encrypt(end)
        s=np.frombuffer(end,dtype=np.uint8)
    with open(secret,'rb') as file1:
        d=file1.read()
    d = len(filetest.test(d))
    data_size=os.path.getsize(secret)
    msg_segment=filetest.segment(s,cover_img)
    filetest.encode_data(msg_segment,cover_img,pasword,file_extension,output,key)
    output_size=os.path.getsize(output)
    print(d,cover_img_len)
    entry_4.insert(END, f'Cover Image size: {cover_size // 1024} KB\n')
    entry_4.insert(END, f'Stego-Image size: {output_size// 1024} KB\n')
    entry_4.insert(END, f'Data size: {data_size // 1024} KB\n')
    entry_4.insert(END,f'Password: {pasword}\n')
    entry_4.insert(END, f'Packets: {msg_segment[1]}\n')
    entry_4.insert(END, 'Encryption method: Symmetric\n')
    entry_4.insert(END, f'Modification Rate: {d/cover_img_len:.5f} %\n')
    messagebox.showinfo(title='Success', message="Hiding successful")



def pass_click():
    global pasword
    l=simpledialog.askstring(title='Password',prompt='Enter Your password',parent=window)
    if l:
        pasword=l.strip()

canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 648,
    width = 931,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    0.0,
    0.0,
    anchor="nw",
    text="Delafuente Steg-Tool",
    fill="#392F2F",
    font=("Georgia", 15 * -1)
)

canvas.create_text(
    71.0,
    102.0,
    anchor="nw",
    text="Cover Image Path",
    fill="#000000",
    font=("Georgia", 15 * -1)
)

canvas.create_text(
    71.0,
    175.0,
    anchor="nw",
    text="Data to be hidden",
    fill="#000000",
    font=("Georgia", 15 * -1)
)

canvas.create_text(
    683.0,
    175.0,
    anchor="nw",
    text="*ZIP for more than one file*",
    fill="#000000",
    font=("Georgia Bold", 15 * -1)
)

canvas.create_text(
    776.0,
    463.0,
    anchor="nw",
    text="Details Report",
    fill="#000000",
    font=("Georgia", 15 * -1)
)

canvas.create_text(
    71.0,
    254.0,
    anchor="nw",
    text="Output Folder",
    fill="#000000",
    font=("Georgia", 15 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    405.0,
    111.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
font=('Georgia',10),
    bg="#FFF8F8",
    fg="#000716",
    highlightthickness=0
)

entry_1.place(
    x=236.0,
    y=100.0,
    width=338.0,
    height=20.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    405.0,
    186.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
font=('Georgia',10),
    bg="#FFF8F8",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=236.0,
    y=175.0,
    width=338.0,
    height=20.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    405.0,
    263.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
font=('Georgia',10),
    bg="#FFF8F8",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=236.0,
    y=252.0,
    width=338.0,
    height=20.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    bg='white',
    highlightthickness=0,
    command=hide_click,
    relief="flat"
)
button_1.place(
    x=405.0,
    y=451.0,
    width=63.0,
    height=31.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
bg='white',
    highlightthickness=0,
    command=file_path,
    relief="flat"
)
button_2.place(
    x=590.0,
    y=102.0,
    width=37.0,
    height=19.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
bg='white',
    highlightthickness=0,
    command=file_path1,
    relief="flat"
)
button_3.place(
    x=590.0,
    y=175.0,
    width=37.0,
    height=19.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
bg='white',
    highlightthickness=0,
    command=pass_click,
    relief="flat"
)
button_4.place(
    x=71.0,
    y=327.0,
    width=181.0,
    height=19.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
bg='white',
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=file_path2,
    relief="flat"
)
button_5.place(
    x=590.0,
    y=254.0,
    width=37.0,
    height=19.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    824.0,
    565.0,
    image=entry_image_4
)
entry_4 = Text(
    bd=0,
    font=('Georgia',10),
    bg="#F6EBEB",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=722.0,
    y=482.0,
    width=204.0,
    height=164.0
)
window.resizable(False, False)
window.mainloop()
