import os
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\dwx1284808\PycharmProjects\pythonProject\Final year project\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("833x454")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 454,
    width = 833,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    175.0,
    227.0,
    image=image_image_1
)

canvas.create_text(
    444.0,
    17.0,
    anchor="nw",
    text="Delafuente Steg-Tool",
    fill="#9B9090",
    font=("Georgia Bold", 30 * -1)
)
def run_hide():
    os.system('Hidepage.py')
def run_extract():
    os.system('Extractpage.py')
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
bg='white',
    highlightthickness=0,
    command=run_hide,
    relief="flat"
)
button_1.place(
    x=504.0,
    y=131.0,
    width=185.0,
    height=43.0
)

canvas.create_text(
    591.0,
    231.0,
    anchor="nw",
    text="Or",
    fill="#000000",
    font=("Georgia Bold", 20 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    bg='white',
    highlightthickness=0,
    command=run_extract,
    relief="flat"
)
button_2.place(
    x=504.0,
    y=328.0,
    width=185.0,
    height=44.0
)
window.resizable(False, False)
window.mainloop()
